version: "2"
plugins:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: .eslintrc
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
