version: "2"
plugins:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: .eslintrc
    checks:
      complexity:
        enabled: false
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
exclude_patterns:
  - "_plugins/jekyll_get.rb"
  - "_plugins/jekyll_minimagick.rb"
