language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
  - gem install bundler
script: JEKYLL_ENV=production bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: ${TRAVIS_BUILD_DIR}/_site
  target_branch: gh-pages
  fqdn: chickenonabun.com
