language: ruby
cache: bundler
branches:
  except:
  - gh-pages
install:
  - gem install bundler
  - npm install mocha
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov yarn run test
  - JEKYLL_ENV=production bundle exec jekyll build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: ${TRAVIS_BUILD_DIR}/_site
  target_branch: gh-pages
  fqdn: chickenonabun.com
