language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
  - gem install bundler
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: chickenonabun.com
  on:
    branch: master
