tagline: "All about fried chicken sandwiches."
logo: /img/chicken.png
url: https://chickenonabun.com

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
