url: "https://chickenonabun.com"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-sitemap
