title: "Chicken On A Bun"
tagline: "Chicken On A Bun - we show you the best fried chicken sandwiches."
description: "Chicken On A Bun is a curated guide to the best fried chicken sandwiches in America. We traveled and visited every restaurant listed and thoroughly taste tested the chicken sandwiches and sides so you can enjoy the good ones."
logo: /assets/icons/chicken.png
url: https://chickenonabun.com

exclude:
  - "assets/images/original"
  - "cc-test-reporter"
  - "coverage"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true

plugins_dir: ./_plugins

plugins:
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap

mini_magick:
  medium:
    source: assets/images/original
    destination: assets/images/medium
    resize: "600x600"
