tagline: "All about fried chicken sandwiches."
logo: /img/chicken.png
url: https://chickenonabun.com

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins_dir: ./_plugins
jekyll_get:
  - data: github
    json: "https://api.github.com/users/stefanthoss/repos"
    cache: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
