name: Jekyll CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Jekyll CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install ruby-mini-magick

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses:  helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          build_only: true
