name: Lint Code Base

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: (_plugins/jekyll_minimagick.rb|assets/css/|LICENSE.md)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSS_FILE_NAME: .stylelintrc.json
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          RUBY_CONFIG_FILE: .rubocop.yml
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_RUBY: true
          VALIDATE_YAML: true
